name: Build and Push to ECR

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    # Dynamically set the environment name based on the branch
    environment:
      name: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    
    - name: Print AWS region
      run: echo "AWS Region: ${{ secrets.AWS_REGION }} 

    - name: Print Github environment
      run: echo "Github Environment: ${{ github.environment }}"

    - name: Print Github ref
      run: echo "Github Ref: ${{ github.ref }}"


    - name: Configure AWS credentials from environment secrets
      uses: aws-actions/configure-aws-credentials@master
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Get current date
      id: date
      run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        IMAGE_URI="${ECR_REGISTRY}/${{ secrets.ECR_REPOSITORY }}/${{ secrets.CONTAINER_NAME }}"
        IMAGE_TAG_LATEST="latest"
        IMAGE_TAG_DATE="${{ env.DATE }}"
        
        docker build -t $IMAGE_URI:$IMAGE_TAG_LATEST .
        
        # Tag with 'latest'
        docker tag $IMAGE_URI:$IMAGE_TAG_LATEST $IMAGE_URI:$IMAGE_TAG_LATEST
        
        # Tag with date
        docker tag $IMAGE_URI:$IMAGE_TAG_LATEST $IMAGE_URI:$IMAGE_TAG_DATE
        
        # Push 'latest' tag
        docker push $IMAGE_URI:$IMAGE_TAG_LATEST
        
        # Push date tag
        docker push $IMAGE_URI:$IMAGE_TAG_DATE

    - name: Verify pushed images
      run: |
        IMAGE_URI="${ECR_REGISTRY}/${{ secrets.ECR_REPOSITORY }}/${{ secrets.CONTAINER_NAME }}"
        aws ecr describe-images --repository-name ${{ secrets.ECR_REPOSITORY }} --image-ids imageTag=$IMAGE_TAG_LATEST
        aws ecr describe-images --repository-name ${{ secrets.ECR_REPOSITORY }} --image-ids imageTag=$IMAGE_TAG_DATE